apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb-tcp
  namespace: kube-system
  annotations: 
    metallb.universe.tf/allow-shared-ip: "key-to-share-172.16.255.53"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.16.255.53
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb-udp
  namespace: kube-system
  annotations: 
    metallb.universe.tf/allow-shared-ip: "key-to-share-172.16.255.53"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.16.255.53
  ports:
    - name: dnstcp
      protocol: UDP
      port: 53
      targetPort: 53