apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev
---
#TODO jane роль admin в рамках Namespace dev
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa:jane:admin
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: jane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev
---
#TODO ken роль view в рамках Namespace dev
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa:ken:view
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: ken