apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-service-monitor
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    any: true
  endpoints:
  - port: nginx-metrics
    interval: 3s